### ISSUE TITLE
[1.12.2] Crash on server startup

### ISSUE THREAD

**Issue by kwpugh** [BrassGoggledCoders/SteamAgeRevolution#6]
Please note: this is a SpongeForge server

crash report:  https://gist.github.com/kwpugh/583cc952728f885d4a09418d83c03410

Adding Steam and Base causes crash at startup

Seems to be ok client side.

**Comment by kwpugh** [comment]
oh, and a fluid hopper might be better named a funnel.

**Comment by kwpugh** [comment]
Does the mod create a config file?

**Comment by warlordjones** [comment]
Will investigate the crash later today, looks like it should be a simple fix through.

As for the fluid hopper, I think it's a more intuitive name than funnel, I'd be intrested to know general consensus on it.

The mod does create a config in the /acronym/ subfolder because it uses the Base library. I just updated the curse forge description to highlight this earlier actually.
